version: "3.9"

services:
  db:
    image: postgres
    container_name: postgres_container_abcd
    restart: always
    environment: 
      - POSTGRES_PASSWORD=admin
    volumes: 
      - ./docker/postgres:/var/lib/postgresql/data
    ports: 
      - "7654:5432"
    networks: 
      - express-network

networks:
  express-network:
